services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgresqlDocker'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5433:${INTERNAL_PORT}
